# Optional C++20 named module support for psi::err (opt-in, off by default).
#
# Adds a target, `psi_err_module` (alias `psi::err_module`), exporting psi::err's public headers
# as `import psi.err;` instead of textual #include. Purely additive: the existing `psi_err`
# INTERFACE target and every consumer vendoring these headers directly are unaffected regardless
# of whether this option exists.
#
# Same shape as psiha/vm's, psiha/functionoid's and psiha/sweater's own module.cmake (see psiha/vm
# PR feat/module-support): the global module fragment carries the STL plus the Boost/psiha deps
# these headers use (boost/assert.hpp, boost/config.hpp, boost/config_ex.hpp,
# boost/throw_exception.hpp and, on Windows, boost/winapi/*) textually - none of these are part of
# psi::err's own exported public surface, only implementation detail; the purview
# (`export extern "C++"`) carries every real header via file(GLOB_RECURSE), filtered to the
# platform this configure targets: win32.hpp is Windows-only (last_win32_error, built on
# boost::winapi + <windows.h>) and is excluded everywhere else, the same shape as psiha/sweater's
# own platform split for its compiled sources.
#
# Toolchain: clang-cl and the GNU-driver clang only; MSVC and GCC get a warning, not a hard error,
# if the option is set there anyway.
#
# Known limitation (inherent to C++ modules, not fixable here): result_or_error.hpp's
# PSI_ERR_PROPAGATE_FAILURE / PSI_ERR_SAVE_RESULT_OR_PROPAGATE_FAILURE convenience macros, and
# PSI_RELEASE_FORCEINLINE, are still only reachable via the textual #include of psi/err/*.hpp -
# a module purview can export declarations but never macros, so an `import psi.err;`-only
# consumer that wants those two macros must also `#include <psi/err/result_or_error.hpp>`.

option( PSI_ERR_MODULE "Build psi.err as a C++20 named module (opt-in; requires clang-cl or clang)" OFF )

if ( PSI_ERR_MODULE )
    if ( NOT ( CMAKE_CXX_COMPILER_ID MATCHES Clang ) )
        message( WARNING "PSI_ERR_MODULE requires clang-cl or clang; ignored on ${CMAKE_CXX_COMPILER_ID}." )
    else()
        if ( CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "MSVC" )
            cmake_path( GET CMAKE_CXX_COMPILER PARENT_PATH _psi_err_llvm_bin )
            find_program( PSI_ERR_CLANG_SCAN_DEPS clang-scan-deps HINTS "${_psi_err_llvm_bin}" REQUIRED )
            string( CONCAT CMAKE_CXX_SCANDEP_SOURCE
                "\"${PSI_ERR_CLANG_SCAN_DEPS}\" -format=p1689 -- <CMAKE_CXX_COMPILER> <DEFINES> <INCLUDES> <FLAGS>"
                " /TP <SOURCE> /c /Fo<OBJECT> /clang:-MT /clang:<DYNDEP_FILE> /clang:-MD /clang:-MF /clang:<DEP_FILE>"
                " > <DYNDEP_FILE>.tmp && \"${CMAKE_COMMAND}\" -E rename <DYNDEP_FILE>.tmp <DYNDEP_FILE>" )
            set( CMAKE_CXX_MODULE_MAP_FORMAT clang )
            set( CMAKE_CXX_MODULE_MAP_FLAG "@<MODULE_MAP_FILE>" )
            set( CMAKE_CXX_COMPILE_BMI "<CMAKE_CXX_COMPILER> <DEFINES> <INCLUDES> <FLAGS> /clang:-o<OBJECT> /clang:--precompile /TP <SOURCE>" )
        endif()

        file( GLOB_RECURSE psi_err_module_headers RELATIVE "${CMAKE_CURRENT_LIST_DIR}/include" "${CMAKE_CURRENT_LIST_DIR}/include/*.hpp" )

        # win32.hpp is Windows-only (last_win32_error: boost::winapi + <windows.h>) - exclude it
        # everywhere else, mirroring psiha/sweater's own platform split for its compiled sources.
        if ( NOT WIN32 )
            list( FILTER psi_err_module_headers EXCLUDE REGEX "win32\\.hpp$" )
        endif()

        set( _psi_err_module_purview "${CMAKE_CURRENT_BINARY_DIR}/psi_err_module_purview.hpp" )
        set( _psi_err_module_content "// Generated by module.cmake - every psi::err public header, cumulative.\n" )
        foreach( h ${psi_err_module_headers} )
            string( APPEND _psi_err_module_content "#include <${h}>\n" )
        endforeach()
        file( WRITE "${_psi_err_module_purview}" "${_psi_err_module_content}" )

        set( _psi_err_module_unit "${CMAKE_CURRENT_BINARY_DIR}/psi_err_module.cppm" )
        file( WRITE "${_psi_err_module_unit}" "\
module;
#ifdef _WIN32
#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include <windows.h>
#undef ERROR
#endif
#ifdef __APPLE__
#include <Availability.h>
#include <TargetConditionals.h>
#endif
#include <cerrno>
#include <cstdint>
#include <cstring>
#include <exception>
#include <new>
#include <stdexcept>
#include <type_traits>
#include <utility>
#include <boost/assert.hpp>
#include <boost/config.hpp>
#include <boost/config_ex.hpp>
#include <boost/throw_exception.hpp>
#ifdef _WIN32
#include <boost/winapi/error_handling.hpp>
#include <boost/winapi/get_last_error.hpp>
#endif
export module psi.err;
export extern \"C++\"
{
#include \"${_psi_err_module_purview}\"
}
" )

        add_library( psi_err_module STATIC )
        add_library( psi::err_module ALIAS psi_err_module )
        target_compile_features( psi_err_module PUBLIC cxx_std_23 )
        target_sources( psi_err_module PUBLIC FILE_SET CXX_MODULES BASE_DIRS "${CMAKE_CURRENT_BINARY_DIR}" FILES "${_psi_err_module_unit}" )
        target_include_directories( psi_err_module PUBLIC "${CMAKE_CURRENT_LIST_DIR}/include" )
        target_link_libraries( psi_err_module PUBLIC Boost::boost )
        target_compile_options( psi_err_module PRIVATE
            $<$<CXX_COMPILER_FRONTEND_VARIANT:MSVC>:/clang:-std=gnu++2c /clang:-Wno-include-angled-in-module-purview /clang:-Wno-reserved-module-identifier>
            $<$<NOT:$<CXX_COMPILER_FRONTEND_VARIANT:MSVC>>:-Wno-include-angled-in-module-purview -Wno-reserved-module-identifier>
        )
    endif()
endif()
